name: Build Status

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: uninstall tbb
        if: matrix.platform == 'ubuntu-latest'
        run: |
          apt list --installed
          sudo apt-get remove libtbb-dev   # TODO (https://github.com/numba/numba/issues/6350#issuecomment-728174860)
 

      - run: |
          pip install pytest

      - run: |
          pip install -r requirements.txt

      - run: |
          PYTHONPATH=. pytest -We
